(function() {
  var scripts = ["/jsdefs.js",
        "/jslex.js",
        "/jsparse.js",
        "/monitor.js",
        "/monprelude.js",
        "/monfundament.js",
        "/monconversion.js",
        "/monecma.js",
        "/monfunbase.js",
        "/monobjbase.js",
        "/monerror.js",
        "/monenv.js",
        "/monfun.js",
        "/monbool.js",
        "/monarray.js",
        "/monregexp.js",
        "/monstring.js",
        "/monnumber.js",
        "/monmath.js",
        "/mondate.js",
        "/monlabel.js",
        "/monglobal.js",
        "/monexec.js",
        "/dom/base.js",
        "/dom/core/node.js",
        "/dom/core/nodelist.js",
        "/dom/core/namednodemap.js",
        "/dom/core/element.js",
        "/dom/core/document.js",
        "/dom/core/attr.js",
        "/dom/html/htmlelement.js",
        "/dom/html/htmldocument.js",
        "/dom/html/htmlcollection.js",
        "/dom/html/htmlformelement.js",
        "/dom/html/htmlinputelement.js",
        "/dom/html/htmlimageelement.js",
        "/dom/html/htmlscriptelement.js",
        "/dom/ext/selection.js",
        "/dom/window.js",
        "/snowfox.js"];

  for (var i in scripts)
    document.write('<script src="http://jsflow.monitor' + scripts[i] + '"></script>');
  document.write('<script type="text/javascript">document.location.hasOwnProperty = {}.hasOwnProperty; document.location.attributes = document.location.parentNode = null; document.location.childNodes = { length: 0 }; JSFlow.monitor.initialize(window);JSFlow.monitor.evaluate("Image = function(){ return {} }, screen = {width: " + screen.width + "}");</script>');
  // document.write('<script src="http://jsflow.monitor/error.js"></script>');
})();